const mappingRows = [
  ['BANDUNG', 'JAWA BARAT', 'CJA,TRG,DGO,GGK,HGM,BDK,TLE,CCD,LBG,UBR,CMI,NJG,BTJ,CKW,CLL,CPT,CSA,GNH,LEM,PDL,CBE,CJG,CJR,CKK,SDL,SGA,SKM,TGE,RJW'],
  ['SOREANG', 'JAWA BARAT', 'SMD,TAS,BJA,CWD,PNL,SOR,CCL,MJY,RCK,CKI,JTW,KAD,MJL,RGA'],
  ['SERANG', 'BANTEN', 'TJO,BLJ,CKA,CSK,KRS,SAG,TGR,BAY,LBU,LWD,MEN,MLP,PDG,RKS,SKE,BJO,BJT,BRS,CKD,CLG,CRS,CWN,GRL,KMT,MER,PBN,PSU,SAM,SEG,LGK,CUG,KJO,MUK,PSK,RJG'],
  ['KARAWANG', 'EASTERN JABOTABEK', 'BGG,DNI,CIB,CBG,LMA,MGB,PBY,STN,TBL,CIK,JBB,CBR,EJI,SMH,SUE,BBL,TAR,CKP,CLM,JTS,KLI,WDS,CPL,KRL,KRW,RDK,TLJ,CBU,PLD,PWK'],
  ['BEKASI', 'EASTERN JABOTABEK', 'BEK,PKY,KLB,KRA,PDE,CNE,PCM,DEP,CSL,SKJ'],
  ['BOGOR', 'EASTERN JABOTABEK', 'BOO,CJU,CRI,CSR,CWI,BJD,CBI,TJH,CAU,CLS,JGL,CSN,GPI,CGD,DMG,JSA,LBI,LWL,KHL,CPS,PAG,CSE,PAR,SPL,CTR,PMU,STL,BGL,CBD,CCR,CKB,JPK,KLU,PLR,CMO,NLD,SGN,SKB,PPG'],
  ['CIREBON', 'JAWA BARAT', 'AWN,CBN,CKC,CKY,JBN,PRD,CLI,KNG,LOS,PAB,SDU,BON,HAR,IMY,JTB,KRM,LSR,PTR,CAS,JCG,KIA,PBS,PGD,PMN,SUB'],
  ['NORTHERN JAKARTA', 'JAKARTA', 'CKG,KDY,MRY,PLM,SMI,SDM,SLP,TGA,KPK,KSB,DTG,JIA,KTZ,KLG,CIL,MRD,KTX,MKR,PDM,STR,TPR'],
  ['SOUTHERN JAKARTA', 'JAKARTA', 'CPP,CID,GBC,GBI,KMY,BIN,CPE,JAG,KAL,KBY,TNK,KMG,PSM,TBE,CBB,CWA,GAN,JTN,KLD,KRG,PSR,PGG,PDK,PGB,RMG'],
  ['TANGERANG', 'BANTEN', 'RMP,SPT,CLD,CKL,CPD,GDS,TAN,CPA,SRH,LKG,PDR,PKU,SRP'],
  ['TASIKMALAYA', 'JAWA BARAT', 'BJS,BNJ,CMS,KAW,MNJ,PAX,CBT,CKJ,CSP,GRU,KDN,LAG,MLB,PMP,WNR,CBL,CIW,KNU,SPA,RJP,TSM'],
] as const;

export const stoMapping: Record<string, { branch: string; regional: string }> =
  Object.fromEntries(
    mappingRows.flatMap(([branch, regional, stoList]) =>
      stoList.split(',').map((sto) => [sto, { branch, regional }])
    )
  );
