const mappingRows = [
  ['CIJAWURA', 'BANDUNG', 'JAWA BARAT', 'CJA,TRG'],
  ['GEGERKALONG', 'BANDUNG', 'JAWA BARAT', 'DGO,GGK,HGM'],
  ['KOPO', 'BANDUNG', 'JAWA BARAT', 'BDK,TLE'],
  ['LEMBONG', 'BANDUNG', 'JAWA BARAT', 'CCD,LBG'],
  ['UJUNG BERUNG', 'BANDUNG', 'JAWA BARAT', 'UBR'],
  ['MAJALENGKA', 'SOREANG', 'JAWA BARAT', 'SMD,TAS,CKI,JTW,KAD,MJL,RGA'],
  ['BANJARAN', 'SOREANG', 'JAWA BARAT', 'BJA,CWD,PNL,SOR'],
  ['MAJALAYA', 'SOREANG', 'JAWA BARAT', 'CCL,MJY,RCK'],
  ['CIMAHI', 'BANDUNG', 'JAWA BARAT', 'CMI,NJG,BTJ,CLL,GNH'],
  ['PADALARANG', 'BANDUNG', 'JAWA BARAT', 'CKW,CPT,CSA,LEM,PDL'],
  ['CIANJUR', 'BANDUNG', 'JAWA BARAT', 'CBE,CJG,CJR,CKK,SDL,SGA,SKM,TGE'],
  ['RAJAWALI', 'BANDUNG', 'JAWA BARAT', 'RJW'],
  ['CIKUPA', 'SERANG', 'BANTEN', 'TJO,BLJ,CKA,CSK,KRS,SAG,TGR'],
  ['PANDEGLANG', 'SERANG', 'BANTEN', 'BAY,LBU,LWD,MEN,PDG,RKS,SKE'],
  ['CILEGON', 'SERANG', 'BANTEN', 'MLP,BJO,CLG,CWN,GRL,MER,PBN,PSU,SAM'],
  ['SERANG', 'SERANG', 'BANTEN', 'BJT,BRS,CKD,CRS,KMT,SEG'],
  ['BANTAR GEBANG', 'KARAWANG', 'EASTERN JABOTABEK', 'BGG,DNI'],
  ['CIBITUNG', 'KARAWANG', 'EASTERN JABOTABEK', 'CIB'],
  ['LEMAHABANG', 'KARAWANG', 'EASTERN JABOTABEK', 'CBG,LMA,MGB,PBY,STN,TBL'],
  ['CIKARANG', 'KARAWANG', 'EASTERN JABOTABEK', 'CIK,JBB'],
  ['SUKARESMI', 'KARAWANG', 'EASTERN JABOTABEK', 'CBR,EJI,SMH,SUE'],
  ['TARUMAJAYA', 'KARAWANG', 'EASTERN JABOTABEK', 'BBL,TAR'],
  ['BEKASI', 'BEKASI', 'EASTERN JABOTABEK', 'BEK'],
  ['PEKAYON', 'BEKASI', 'EASTERN JABOTABEK', 'PKY'],
  ['KALIABANG', 'BEKASI', 'EASTERN JABOTABEK', 'KLB'],
  ['KRANJI', 'BEKASI', 'EASTERN JABOTABEK', 'KRA'],
  ['PONDOKGEDE', 'BEKASI', 'EASTERN JABOTABEK', 'PDE'],
  ['BOGOR', 'BOGOR', 'EASTERN JABOTABEK', 'BOO'],
  ['CIAWI', 'BOGOR', 'EASTERN JABOTABEK', 'CJU,CRI,CSR,CWI'],
  ['CIBINONG', 'BOGOR', 'EASTERN JABOTABEK', 'BJD,CBI,TJH'],
  ['CILEUNGSI', 'BOGOR', 'EASTERN JABOTABEK', 'CAU,CLS,JGL'],
  ['GUNUNG PUTRI', 'BOGOR', 'EASTERN JABOTABEK', 'CSN,GPI'],
  ['DRAMAGA', 'BOGOR', 'EASTERN JABOTABEK', 'CGD,DMG,JSA,LBI,LWL'],
  ['KEDUNGHALANG', 'BOGOR', 'EASTERN JABOTABEK', 'KHL'],
  ['PAGELARAN', 'BOGOR', 'EASTERN JABOTABEK', 'CPS,PAG'],
  ['SEMPLAK', 'BOGOR', 'EASTERN JABOTABEK', 'CSE,PAR,SPL'],
  ['SENTUL', 'BOGOR', 'EASTERN JABOTABEK', 'CTR,PMU,STL'],
  ['CINERE', 'BEKASI', 'EASTERN JABOTABEK', 'CNE,PCM'],
  ['RAWAGENI', 'BEKASI', 'EASTERN JABOTABEK', 'DEP'],
  ['SUKMAJAYA', 'BEKASI', 'EASTERN JABOTABEK', 'CSL,SKJ'],
  ['CIREBON', 'CIREBON', 'JAWA BARAT', 'AWN,CBN,CKC,CKY,JBN,PRD'],
  ['KUNINGAN', 'CIREBON', 'JAWA BARAT', 'CLI,KNG,LOS,PAB,SDU'],
  ['INDRAMAYU', 'CIREBON', 'JAWA BARAT', 'BON,HAR,IMY,JTB,KRM,LSR,PTR'],
  ['SUBANG', 'CIREBON', 'JAWA BARAT', 'CAS,JCG,KIA,PBS,PGD,PMN,SUB'],
  ['CENGKARENG', 'NORTHERN JAKARTA', 'JAKARTA', 'CKG,DTG'],
  ['KEDOYA', 'NORTHERN JAKARTA', 'JAKARTA', 'KDY'],
  ['MERUYA', 'NORTHERN JAKARTA', 'JAKARTA', 'MRY'],
  ['SA PALMERAH & PETAMBURAN', 'NORTHERN JAKARTA', 'JAKARTA', 'PLM'],
  ['SEMANGGI', 'NORTHERN JAKARTA', 'JAKARTA', 'SMI'],
  ['SLIPI', 'NORTHERN JAKARTA', 'JAKARTA', 'SDM,SLP'],
  ['TEGAL ALUR', 'NORTHERN JAKARTA', 'JAKARTA', 'TGA,JIA'],
  ['KOSAMBI', 'NORTHERN JAKARTA', 'JAKARTA', 'KPK,KSB'],
  ['CEMPAKA PUTIH', 'SOUTHERN JAKARTA', 'JAKARTA', 'CPP'],
  ['CIDENG', 'SOUTHERN JAKARTA', 'JAKARTA', 'CID'],
  ['CIKINI', 'SOUTHERN JAKARTA', 'JAKARTA', 'GBC'],
  ['KEMAYORAN', 'SOUTHERN JAKARTA', 'JAKARTA', 'GBI,KMY'],
  ['BINTARO', 'SOUTHERN JAKARTA', 'JAKARTA', 'BIN'],
  ['CIPETE', 'SOUTHERN JAKARTA', 'JAKARTA', 'CPE'],
  ['JAGAKARSA', 'SOUTHERN JAKARTA', 'JAKARTA', 'JAG'],
  ['KALIBATA', 'SOUTHERN JAKARTA', 'JAKARTA', 'KAL'],
  ['KEBAYORAN', 'SOUTHERN JAKARTA', 'JAKARTA', 'KBY,TNK'],
  ['KEMANG', 'SOUTHERN JAKARTA', 'JAKARTA', 'KMG'],
  ['PASAR MINGGU', 'SOUTHERN JAKARTA', 'JAKARTA', 'PSM'],
  ['TEBET', 'SOUTHERN JAKARTA', 'JAKARTA', 'TBE'],
  ['GANDARIA', 'SOUTHERN JAKARTA', 'JAKARTA', 'CBB,GAN'],
  ['CAWANG', 'SOUTHERN JAKARTA', 'JAKARTA', 'CWA'],
  ['JATINEGARA', 'SOUTHERN JAKARTA', 'JAKARTA', 'JTN'],
  ['KLENDER', 'SOUTHERN JAKARTA', 'JAKARTA', 'KLD'],
  ['KRANGGAN', 'SOUTHERN JAKARTA', 'JAKARTA', 'KRG'],
  ['PASAR REBO', 'SOUTHERN JAKARTA', 'JAKARTA', 'PSR'],
  ['PENGGILINGAN', 'SOUTHERN JAKARTA', 'JAKARTA', 'PGG'],
  ['PONDOK KELAPA', 'SOUTHERN JAKARTA', 'JAKARTA', 'PDK,PGB'],
  ['RAWAMANGUN', 'SOUTHERN JAKARTA', 'JAKARTA', 'RMG'],
  ['MANGGA BESAR', 'NORTHERN JAKARTA', 'JAKARTA', 'KTZ'],
  ['KELAPA GADING', 'NORTHERN JAKARTA', 'JAKARTA', 'KLG'],
  ['CILINCING', 'NORTHERN JAKARTA', 'JAKARTA', 'CIL,MRD'],
  ['KOTA', 'NORTHERN JAKARTA', 'JAKARTA', 'KTX'],
  ['MUARA KARANG', 'NORTHERN JAKARTA', 'JAKARTA', 'MKR'],
  ['PADEMANGAN SUNTER', 'NORTHERN JAKARTA', 'JAKARTA', 'PDM,STR'],
  ['TANJUNG PRIOK', 'NORTHERN JAKARTA', 'JAKARTA', 'TPR'],
  ['CIKAMPEK', 'KARAWANG', 'EASTERN JABOTABEK', 'CKP,CLM,JTS,KLI,WDS'],
  ['KARAWANG', 'KARAWANG', 'EASTERN JABOTABEK', 'CPL,KRL,KRW,RDK,TLJ'],
  ['PURWAKARTA', 'KARAWANG', 'EASTERN JABOTABEK', 'CBU,PLD,PWK'],
  ['CIBADAK', 'BOGOR', 'EASTERN JABOTABEK', 'BGL,CBD,CCR,CKB,JPK,KLU,PLR'],
  ['SUKABUMI', 'BOGOR', 'EASTERN JABOTABEK', 'CMO,NLD,SGN,SKB'],
  ['SERPONG', 'TANGERANG', 'BANTEN', 'RMP,SRP'],
  ['LEGOK', 'TANGERANG', 'BANTEN', 'LGK,PPG'],
  ['LEGOK', 'TANGERANG', 'BANTEN', 'CUG'],
  ['PASAR KEMIS', 'TANGERANG', 'BANTEN', 'KJO,MUK,PSK,RJG'],
  ['GANDASARI', 'TANGERANG', 'BANTEN', 'SPT,GDS'],
  ['CILEDUG', 'TANGERANG', 'BANTEN', 'CLD'],
  ['CIPONDOH', 'TANGERANG', 'BANTEN', 'CKL,CPD'],
  ['TANGERANG', 'TANGERANG', 'BANTEN', 'TAN'],
  ['CIPUTAT', 'TANGERANG', 'BANTEN', 'CPA,SRH'],
  ['LENGKONG', 'TANGERANG', 'BANTEN', 'LKG'],
  ['PONDOK AREN', 'TANGERANG', 'BANTEN', 'PDR,PKU'],
  ['CIAMIS', 'TASIKMALAYA', 'JAWA BARAT', 'BJS,BNJ,CMS,KAW,MNJ,PAX'],
  ['GARUT', 'TASIKMALAYA', 'JAWA BARAT', 'CBT,CSP,GRU,KDN,LAG,MLB'],
  ['SINGAPARNA', 'TASIKMALAYA', 'JAWA BARAT', 'CKJ,PMP,WNR,CBL,CIW,KNU,SPA'],
  ['TASIKMALAYA', 'TASIKMALAYA', 'JAWA BARAT', 'RJP,TSM'],
] as const;

export const stoMapping: Record<string, { serviceArea: string; branch: string; regional: string }> =
  Object.fromEntries(
    mappingRows.flatMap(([serviceArea, branch, regional, stoList]) =>
      stoList.split(',').map((sto) => [sto, { serviceArea, branch, regional }])
    )
  );

const normalizeHeader = (header: string) => header.trim().toUpperCase().replace(/\s+/g, '_');

export const getStoCode = (row: Record<string, unknown>) => {
  const normalizedRow = Object.fromEntries(
    Object.entries(row).map(([header, value]) => [normalizeHeader(header), value])
  );

  return [normalizedRow.STO, normalizedRow.WORKZONE]
    .map((value) => String(value ?? '').trim().toUpperCase())
    .find((value) => value !== '') || '';
};

export const addMappingColumns = (rows: Record<string, unknown>[]) => rows.map((row) => {
  const mapping = stoMapping[getStoCode(row)];
  const uploadedColumns = Object.fromEntries(
    Object.entries(row).filter(([header]) =>
      !['BRANCH', 'REGION', 'SERVICE_AREA'].includes(normalizeHeader(header))
    )
  );

  return {
    BRANCH: mapping?.branch || '',
    REGION: mapping?.regional || '',
    'SERVICE AREA': mapping?.serviceArea || '',
    ...uploadedColumns,
  };
});
